### ISSUE TITLE
Auto trigger deployments when superset/trino configmaps are updated

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#411]
Ideally the solution would also be application to all configmaps -> deployments in general. 

Suggestion: 
- [x] install [Reloader](https://github.com/stakater/Reloader) 
- [x] disable ODH update for configmaps/secrets (@anishasthana should know how to do this, so he's a good contact here),
- [x] bring configmaps/secrets, under management by argocd, so move them here: https://github.com/operate-first/apps/tree/master/kfdefs
- [x] add the annotations to these configmap/secrets that will make reloader trigger new deployments about configmap change.

**Comment by HumairAK** [comment]
Did this for osc trino dev instance: https://github.com/operate-first/apps/tree/master/kfdefs/overlays/osc/osc-cl1/trino-dev/configs 

Works fine, let's propogate this to the other deployments.

**Comment by dystewart** [comment]
@HumairAK 

I've installed Reloader in my Quicklab cluster using kustomize. 
Here is the the link to the the kustomize resources from Stakater Github page: [reloader](https://github.com/stakater/Reloader/tree/master/deployments/kubernetes)

Here is my kustomization.yaml file:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/stakater/Reloader/deployments/kubernetes
patchesStrategicMerge:
  - patch.yaml
namespace: reloader
```

Here is the patch.yaml to eliminate a security context error:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader-reloader
spec:
  template:
    spec:
      securityContext: NULL
```

After applying with `kubectl apply -k` The deployment and pods build successfully and the Reloader pod is up and running. 

Looking into the logs of the Reloader pod however reveals there is some access control error preventing the reloader service account from listing deploymentconfigs in any namespace in the cluster.

Here is one line from the log for reference:
`time="2021-12-01T21:22:04Z" level=error msg="Failed to list deploymentConfigs deploymentconfigs.apps.openshift.io is forbidden: User \"system:serviceaccount:reloader:reloader-reloader\" cannot list resource \"deploymentconfigs\" in API group \"apps.openshift.io\" in the namespace \"openshift-monitoring\""`

**Comment by HumairAK** [comment]
@dystewart yeah, so the rbac for reloader doesn't take into account `deploymentconfigs` which is a resource introduced in OCP and not available natively in k8s. 

But let's back up and see what's going on:

So we know that the service account it's talking about is called `reloader-reloader`, and we know that this is the `clusterrole` it's given: 
https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/manifests/clusterrole.yaml

We know this because it's given this role via this `clusterrolebinding` : https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/manifests/clusterrolebinding.yaml

Looking at the `clusterrole` in detail, we see that [here](https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/manifests/clusterrole.yaml#L18) in the rules, there is no permission being granted for `deploymentconfigs`. So you will have to patch that in. Note that you can't just add it to the list alongside the `deployment`, `daemonsets`, etc. Because `deploymentconfigs` belong to the `apps.openshift.io` api group, and not `apps` (to which `deployment` belongs). 

So you'll need to create a separate section, and like so: 

```
  - apiGroups:
      - "apps.openshift.io"
    resources:
      - deploymentconfigs
    verbs:
      - list
      - get
      - update
      - patch
```

Further reading: 
https://docs.openshift.com/container-platform/4.9/authentication/using-rbac.html

**Comment by dystewart** [comment]
@HumairAK This all makes more sense now and it was good to see it in action. In this case, the `clusterrole` defines the rules for the `serviceaccount`. The `clusterrolebinding` is what associates the two. 

After patching in the `deploymentconfigs` rules in the `clusterrole`:

```
kind: ClusterRole
metadata:
  name: reloader-reloader-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
      - update
      - patch
  - apiGroups:
      - "apps.openshift.io"
    resources:
      - deploymentconfigs
    verbs:
      - list
      - get
      - update
      - patch
```

After this patch we made another patch to the `deployment` in which we update the container image to pull from quay as opposed to Docker (to avoid rate limiting issues):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader-reloader
spec:
  template:
    spec:
      containers:
      - image: "quay.io/operate-first/reloader:v0.0.103-1"
        name: reloader-reloader
      securityContext: NULL
```

With these patches in place, if we apply our kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/stakater/Reloader/deployments/kubernetes
patchesStrategicMerge:
  - patch.yaml
  - clusterrole_patch.yaml
namespace: reloader
```

We can see the deployment is successful and the reloader `pod` is monitoring all our namespaces in quicklab for changes to `configmaps` and `secrets` as we can see here in the pod's logs:

![Screenshot from 2021-12-07 07-54-42](https://user-images.githubusercontent.com/84931428/145032770-c8147966-dcd6-46c9-9fa7-8f6223d5c61f.png)

**Comment by dystewart** [comment]
As seen in the previous message the Reloader pod is up and running so let's make sure it's actually monitoring our namespaces for changes to configMaps and secrets. 

As a proof of concept I spun up a deployment running an instance of Eclipse Mosquitto, which is an open source MQTT broker. The application itself is not important for the demonstration, I chose it because of the simple setup. In the Mosquitto pod I have mounted a configMap and a secret to see if we can trigger redeployment via Reloader.

Here are the manifests I used for testing: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "mosquitto-secret-file"
    configmap.reloader.stakater.com/reload: "mosquitto-config-file"
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: quay.io/dystewar/mosquitto
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-conf
              mountPath: /mosquitto/config
            - name: mosquitto-secret
              mountPath: /mosquitto/secret  
      volumes:
        - name: mosquitto-conf
          configMap:
            name: mosquitto-config-file
        - name: mosquitto-secret
          secret:
            secretName: mosquitto-secret-file

---

apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret-file
type: Opaque
data:
  secret.file: |
    c29tZXN1cGVyc2VjcmV0IGZpbGUgY29udGVudHMgbm9ib2R5IHNob3VsZCBzZWU=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-file
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001

```

Notice the annotations in the deployment with are monitored by Reloader:
```
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "mosquitto-secret-file"
    configmap.reloader.stakater.com/reload: "mosquitto-config-file"
```

Now if we make changes to the `configmap` and `secret` that we mounted we expect to see our Reloader pod detect these changes in logs and we should see our Mosquitto pod redeployed as a result. And indeed we do!

Here is what the Reloader logs look like after making changes to the tracked assets:
